### ISSUE TITLE
Docs for `Sequel.extension`

### ISSUE THREAD

**Issue by m0n9oose** [pgvector/pgvector-ruby#3]
Please add some docs/examples for use-case without `Sequel::Model`.

I have pretty minimal experimental ruby app built with Sequel and `pgvector` plugin, but struggle to enable it:

```
/Users/u/.rvm/rubies/ruby-3.3.2/lib/ruby/3.3.0/bundled_gems.rb:74:in `require': cannot load such file -- sequel/extensions/pgvector (LoadError)
	from /Users/u/.rvm/rubies/ruby-3.3.2/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /Users/u/.rvm/gems/ruby-3.3.2@pgvector_app/gems/sequel-5.82.0/lib/sequel/core.rb:158:in `block in extension'
	from /Users/u/.rvm/gems/ruby-3.3.2@pgvector_app/gems/sequel-5.82.0/lib/sequel/core.rb:158:in `each'
	from /Users/u/.rvm/gems/ruby-3.3.2@pgvector_app/gems/sequel-5.82.0/lib/sequel/core.rb:158:in `extension'
	from /Users/u/.rvm/gems/ruby-3.3.2@pgvector_app/gems/sequel-5.82.0/lib/sequel/dataset/query.rb:207:in `extension'
	from (irb):2:in `block in <top (required)>'
	from /Users/u/dev/hobby/ollama-index/lib/postgres.rb:39:in `query'
	from (irb):2:in `<main>'
	from <internal:kernel>:187:in `loop'
	from bin/console.rb:9:in `<main>'
```

```ruby
require 'logger'
require 'sequel'
require 'pgvector'

EXTENSIONS = [:pgvector]
CONNECTIONS_SETTINGS = {:adapter=>"postgres", :host=>"localhost", :database=>"pgvector_app"}

def connect
  Sequel.connect(CONNECTIONS_SETTINGS).tap do |cnt|
    cnt.loggers << Logger.new(STDOUT)
    EXTENSIONS.each { cnt.extension(_1) }
  end
end

connect
```

**Comment by ankane** [comment]
Hi @m0n9oose, here's an example without `Sequel::Model`.

```ruby
require "sequel"

DB = Sequel.connect("postgres://localhost/pgvector_example")

DB.run("CREATE EXTENSION IF NOT EXISTS vector")
DB.run("CREATE TABLE items (id bigserial PRIMARY KEY, embedding vector(3))")

DB[:items].insert(embedding: "[1,2,3]")

p DB[:items].order(Sequel.lit("embedding <-> ?", "[1,2,3]")).limit(5).to_a
```

You can optionally use the gem to convert between Ruby and the pgvector text format.

```ruby
require "pgvector"

p Pgvector.encode([1, 2, 3]) # "[1.0,2.0,3.0]"
p Pgvector.decode("[1,2,3]") # [1.0, 2.0, 3.0]
```

**Comment by m0n9oose** [comment]
Thanks for looking into this @ankane ❤️ 
I was able to make it work as an extension but my code is very raw so I hesitate to make a PR :)
In case if you interested in adding extension support:

```diff
diff --git c/lib/sequel/extensions/pgvector.rb i/lib/sequel/extensions/pgvector.rb
new file mode 100644
index 0000000..23557e7
--- /dev/null
+++ i/lib/sequel/extensions/pgvector.rb
@@ -0,0 +1,9 @@
+require 'pgvector'
+require 'sequel/plugins/pgvector'
+
+module Sequel
+  module Pgvector
+  end
+
+  Dataset.register_extension(:pgvector, Sequel::Plugins::Pgvector::DatasetMethods)
+end
```

**Comment by ankane** [comment]
Thanks @m0n9oose, added in the commit above.
